import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'ar' | 'en' | 'ku' | 'fa' | 'tr' | 'es' | 'ru' | 'de';

// Comprehensive English Translation Dictionary
const enTranslations: Record<string, string> = {
  // TruCast Custom Keys
  "home_subtitle": "Latest news and posts",
  "stories_title": "Daily Stories",
  "stories_expire_hint": "Expires after 24 hours",
  "add_story": "Add Story",
  "watch_now": "Watch Now",
  "live_badge": "LIVE",
  "trending_now": "Trending Now",
  "search_posts_placeholder": "Search posts...",
  "profile_design_title": "Profile Design",
  "premium_feature": "Premium Feature",
  "premium_exclusive": "Exclusive to PREMIUM",
  "background_color": "Background Color",
  "font_type": "Font Type",
  "font_inter": "Inter (Default)",
  "font_mono": "Mono (Technical)",
  "font_serif": "Serif (Classic)",
  "font_black": "Black (Ultra Bold)",
  "font_arabic_mono": "Arabic Mono",
  "color_default": "Default",
  "color_royal_blue": "Royal Blue",
  "color_deep_purple": "Deep Purple",
  "color_emerald": "Emerald",
  "color_dark_red": "Dark Red",
  "color_velvet_orange": "Velvet Orange",
  "color_solid_gray": "Solid Gray",
  "color_absolute_black": "Absolute Black",
  "color_cold_dawn": "Cold Dawn",
  "color_purple_dusk": "Purple Dusk",
  "color_red_energy": "Red Energy",
  "color_sand_dune": "Sand Dune",
  "chats_title": "Conversations",
  "all_chats": "All",
  "chat_groups": "Groups",
  "chat_channels": "Channels",
  "direct_messages": "DMs",
  "no_messages_in_channel": "No messages in this channel",
  "start_conversation_now": "Start conversation now",
  "filter_newest": "Newest",
  "filter_oldest": "Oldest",
  "filter_most_active": "Trending",

  // Navigation / Tabs
  "الرئيسية": "Home",
  "البث المباشر": "Live",
  "إضافة": "Add",
  "ريلز": "Reels",
  "حسابي": "Profile",
  "الرسائل": "Messages",
  "الإعدادات": "Settings",
  "إعدادات الحساب": "Account Settings",
  "تسجيل الخروج": "Log Out",
  "تسجيل الخروج من جميع الأجهزة": "Log Out All Devices",
  "حريتك في التعبير محمية بخصوصية مطلقة": "Your freedom of expression is protected with absolute privacy.",
  "ضحك": "Laughing",
  "متحمس": "Excited",
  "شكراً": "Thank you",
  "مبروك": "Congrats",
  "مندهش": "Surprised",
  "حزين": "Sad",
  "غاضب": "Angry",
  "نعم": "Yes",
  "لا": "No",
  "سلام": "Hello",
  "إدراج صورة GIF": "Insert GIF",
  "ابحث عن صور GIF...": "Search GIFs...",
  "الشائع": "Trending",
  "إعادة المحاولة": "Retry",
  "لم يتم العثور على نتائج": "No results found",
  "فشل الاتصال بخدمة GIFs": "Failed to connect to GIF service",
  "تم تحميل الملف الصوتي: ": "Audio file loaded: ",
  "فشل تشغيل الملف الصوتي محلياً": "Failed to play audio file locally",
  "اختر ملف صوتي من جهازك (MP3)": "Choose an audio file from your device (MP3)",
  "سيتم بث الصوت مباشرة بنقاء رقمي كامل": "Audio will be streamed live in full digital clarity",
  "الحجم:": "Size:",
  "ميجابايت": "MB",
  "إيقاف تام": "Stop",
  "إيقاف مؤقت": "Pause",
  "تشغيل": "Play",
  "تغيير الملف": "Change File",

  // Feed / Posts / Stories
  "قصة جديدة": "New Story",
  "ذكاء اصطناعي": "AI Assistant",
  "منشور نصي": "Text Post",
  "صورة / فيديو": "Photo / Video",
  "مقطع ريلز": "Reel Video",
  "اسحب للتحديث": "Pull to refresh",
  "اترك للتحديث": "Release to refresh",
  "جاري التحديث...": "Refreshing...",
  "لا توجد منشورات": "No posts found",
  "التعليقات": "Comments",
  "أضف تعليقاً...": "Add a comment...",
  "نشر": "Post",
  "مشاركة": "Share",
  "إعجاب": "Like",
  "متابعة": "Follow",
  "إلغاء المتابعة": "Unfollow",
  "مراسلة": "Message",
  "بحث": "Search",
  "الرائجة": "Trending",
  "قصص نشطة": "Active Stories",
  "البحث عن منشورات...": "Search posts...",
  "ماذا يدور في ذهنك؟": "What's on your mind?",
  "المنشور متاح للجميع": "Public Post",
  "المشتركين المميزين فقط": "Premium Subscribers Only",
  "خيارات التصويت": "Poll Options",
  "إضافة خيار": "Add Option",
  "سؤال الاستطلاع": "Poll Question",
  "إنشاء منشور": "Create Post",
  "تم نشر المنشور بنجاح!": "Post published successfully!",
  "حدث خطأ أثناء النشر": "Error publishing post",
  "القصص اليومية": "Daily Stories",
  "بماذا تفكر؟": "What's on your mind?",
  "بث مباشر نشط": "Active Live Streams",
  "صناع محتوى مقترحون": "Suggested Creators",
  "جاري النشر...": "Posting...",

  // Profile Screen
  "المنشورات": "Posts",
  "المتابِعون": "Followers",
  "المتابَعون": "Following",
  "متابع": "Follower",
  "يتابع": "Following",
  "تعديل الملف الشخصي": "Edit Profile",
  "النشاط": "Activity",
  "الإحصائيات": "Statistics",
  "لا توجد منشورات لهذا المستخدم": "No posts for this user",
  "لا توجد مقاطع ريلز": "No reels found",
  "تأكيد إلغاء المتابعة": "Confirm Unfollow",
  "هل أنت متأكد من رغبتك في إلغاء متابعة": "Are you sure you want to unfollow",
  "نقاط اكتمال ملفك الشخصي": "Profile Completeness Score",
  "اكتمل": "Completed",
  "تحديث الصورة الشخصية": "Update Profile Picture",
  "تحديث السيرة الذاتية": "Update Bio",
  "تحديث اسم المستخدم": "Update Username",

  // Settings Menu
  "الحساب": "Account",
  "المزيد": "More",
  "تعديل البيانات الشخصية": "Edit Personal Data",
  "تغيير البريد الإلكتروني": "Change Email Address",
  "كلمة المرور والأمان": "Password & Security",
  "خصوصية الحساب": "Account Privacy",
  "قائمة الحظر": "Blocked List",
  "المظهر": "Appearance",
  "تخصيص الأيقونات": "Customize Icons",
  "تصميم الملف الشخصي": "Profile Design",
  "توثيق الحساب (Verification)": "Verification",
  "إحصائيات الحساب": "Account Statistics",
  "التنبيهات": "Notifications",
  "المحفوظات": "Favorites",
  "حول TruCast": "About TruCast",
  "مركز المساعدة": "Help Center",
  "سياسة الخصوصية": "Privacy Policy",
  "اللغة / Language": "Language",
  "تغيير لغة التطبيق": "Change Application Language",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "Select your preferred language for the whole app",
  "اللغة الحالية": "Current Language",

  // Personal Info Settings
  "الاسم المعروض": "Display Name",
  "اسم المستخدم": "Username",
  "السيرة الذاتية (Bio)": "Bio",
  "أخبر المجتمع عن نفسك...": "Tell the community about yourself...",
  "اسم المستخدم متاح": "Username is available",
  "اسم المستخدم غير متاح": "Username is not available",
  "جاري التحقق...": "Checking...",
  "تغيير الصورة الشخصية": "Change Profile Picture",
  "حفظ التغييرات": "Save Changes",

  // Email Settings
  "البريد الإلكتروني الحالي": "Current Email Address",
  "البريد الإلكتروني الجديد": "New Email Address",
  "تحديث البريد الإلكتروني": "Update Email Address",
  "تم تحديث البريد الإلكتروني بنجاح": "Email updated successfully",

  // Security Settings
  "كلمة المرور الحالية": "Current Password",
  "كلمة المرور الجديدة": "New Password",
  "تأكيد كلمة المرور الجديدة": "Confirm New Password",
  "تحديث كلمة المرور": "Update Password",
  "التحقق بخطوتين (2FA)": "Two-Factor Authentication (2FA)",
  "تفعيل التحقق بخطوتين": "Enable Two-Factor Authentication",
  "تعطيل التحقق بخطوتين": "Disable Two-Factor Authentication",
  "الأجهزة المرخصة والنشطة": "Licensed & Active Devices",
  "هذا الجهاز": "This Device",
  "آخر نشاط": "Last Active",
  "إلغاء الترخيص": "Revoke Access",
  "هل أنت متأكد من رغبتك في إلغاء الترخيص لهذا الجهاز؟ سيتم تسجيل خروجه فوراً.": "Are you sure you want to revoke access for this device? It will be logged out immediately.",
  "تم إلغاء ترخيص الجهاز بنجاح.": "Device access revoked successfully.",

  // Privacy Settings
  "عرض قائمة المتابعين": "Show Followers List",
  "السماح للآخرين برؤية قائمة المتابعين لك": "Allow others to see your followers list",
  "عرض قائمة المتابَعين": "Show Following List",
  "السماح للآخرين برؤية قائمة الحسابات التي تتابعها": "Allow others to see the accounts you follow",
  "إظهار عدد المنشورات في الملف الشخصي": "Show number of posts on profile",
  "عرض حالة آخر ظهور": "Show Last Seen Status",
  "السماح للآخرين برؤية متى كنت متصلاً": "Allow others to see when you were online",
  "التحليلات مجهولة الهوية": "Anonymous Analytics",
  "المساهمة في الإحصائيات العامة دون كشف الهوية": "Contribute to general stats anonymously",

  // Appearance Settings
  "مظهر التطبيق": "Application Appearance",
  "الوضع الداكن": "Dark Mode",
  "الوضع الفاتح": "Light Mode",
  "كلاسيكي وأنيق": "Classic & Elegant",
  "نقي ومنعش": "Pure & Fresh",
  "الألوان المميزة (Premium)": "Premium Highlight Colors",
  "خلفيات الدردشة المخصصة (Premium)": "Custom Chat Wallpapers (Premium)",
  "تعديل المظهر": "Edit Appearance",

  // Custom Navigation Icons
  "تخصيص أيقونات التنقل": "Customize Navigation Icons",
  "اختر الأيقونات التي تفضلها لشريط التنقل السفلي والجانبي": "Choose your preferred icons for the navigation bar",

  // Notifications Settings
  "إشعارات الرسائل": "Message Notifications",
  "تلقي تنبيهات عند وصول رسائل جديدة": "Receive alerts when new messages arrive",
  "إشعارات البث المباشر": "Live Stream Notifications",
  "تلقي تنبيهات عند بدء بث مباشر من الحسابات التي تتابعها": "Receive alerts when followed accounts go live",
  "تفعيل إشعارات المتصفح": "Enable Browser Notifications",

  // Favorites / Saved Favorites
  "المحفوظات Saved": "Saved Favorites",
  "لا توجد منشورات محفوظة": "No saved posts found",
  "لا توجد مقاطع ريلز محفوظة": "No saved reels found",

  // Verification Settings
  "الحصول على شارة التوثيق الزرقاء لزيادة المصداقية": "Get the blue verification badge to increase credibility",
  "طلب التوثيق الخاص بك تحت المراجعة حالياً.": "Your verification request is currently under review.",
  "حسابك موثق بالفعل وتحمل الشارة الزرقاء!": "Your account is already verified with the blue checkmark!",
  "تقديم طلب التوثيق": "Submit Verification Request",
  "لماذا يجب توثيق حسابك؟": "Why verify your account?",

  // Chat Screen / Messages List
  "البحث عن محادثات...": "Search chats...",
  "نشط الآن": "Active Now",
  "الكل": "All",
  "المجموعات": "Groups",
  "القنوات": "Channels",
  "الخاص": "Private",
  "المحفوظة": "Saved",
  "محادثاتك": "Your Chats",
  "رسائل مميزة بنجمة": "Starred Messages",
  "الرسائل المحفوظة (الرسائل الذاتية)": "Saved Messages (Self Notes)",
  "بدء محادثة جديدة": "Start New Conversation",
  "إنشاء مجموعة جديدة": "Create New Group",
  "إنشاء قناة جديدة": "Create New Channel",
  "أرشيف": "Archive",
  "تأكيد الحذف": "Confirm Delete",
  "هل أنت متأكد من حذف هذه المحادثة بالكامل؟": "Are you sure you want to delete this chat completely?",

  // Chat conversation
  "كتابة رسالة...": "Type a message...",
  "إرسال": "Send",
  "رسالة صوتية": "Voice message",
  "جاري التسجيل...": "Recording...",
  "مكالمة فيديو": "Video Call",
  "مكالمة صوتية": "Voice Call",
  "معلومات المحادثة": "Chat Info",
  "أعضاء المجموعة": "Group Members",
  "إضافة عضو": "Add Member",
  "غادر المجموعة": "Leave Group",

  // Live stream screens
  "البث المباشر النشط": "Active Live Streams",
  "إنشاء بث مباشر": "Create Live Stream",
  "عنوان البث": "Stream Title",
  "بدء البث": "Go Live",
  "إنهاء البث": "End Stream",
  "مستمع": "Listener",
  "متحدث": "Speaker",
  "التعليقات المباشرة": "Live Comments",
  "معرف:": "ID:",
  "إعدادات البث المباشر ⚙️": "Live Stream Settings ⚙️",
  "لوحة التحكم الإدارية للمضيف وإشراف البث": "Host Admin Dashboard & Moderation",
  "عام ⚙️": "General ⚙️",
  "الطلبات ✋": "Requests ✋",
  "المشرفون 🛡️": "Moderators 🛡️",
  "المكتومون 🔇": "Muted 🔇",
  "جودة بث الفيديو": "Video Quality",
  "تم تحديد جودة البث:": "Broadcast quality set to:",
  "حجم صوت المايكروفون": "Microphone Volume",
  "تم كتم الصوت 🔇": "Audio muted 🔇",
  "تم إلغاء كتم الصوت 🔊": "Audio unmuted 🔊",
  "لا توجد طلبات انضمام معلقة حالياً ✋": "No pending join requests currently ✋",
  "قبول 👍": "Accept 👍",
  "رفض": "Reject",
  "لا يوجد مشرفون معينون لهذا البث حالياً 🛡️": "No designated moderators for this stream yet 🛡️",
  "إلغاء الإشراف 🛡️": "Demote Moderator 🛡️",
  "لا يوجد مستخدمون مكتومون في هذا البث حالياً 🔇": "No muted users in this stream currently 🔇",
  "فك الكتم 🔊": "Unmute 🔊",
  "لا يوجد مستخدمون محظورون من هذا البث حالياً 🚫": "No banned users from this stream currently 🚫",
  "إلغاء الحظر 🔓": "Unban 🔓",
  "تطبيق وحفظ التعديلات ✅": "Apply & Save Changes ✅",

  // Live stream sharing and overlays
  "محادثة خاصة": "Private Chat",
  "الرجاء تحديد قناة واحدة على الأقل للإرسال": "Please select at least one channel to send",
  "بث مباشر حي": "Live Stream",
  "انضم إلى البث المباشر المثير:": "Join the exciting live stream:",
  "اضغط على البطاقة للدخول الفوري.": "Click the card for instant entry.",
  "🔴 بطاقة مشاركة بث مباشر تفاعلية": "🔴 Interactive live stream share card",
  "تمت مشاركة البث للمحادثات المحددة بنجاح! 🎉": "Stream shared with selected chats successfully! 🎉",
  "حدث خطأ أثناء الإرسال": "Error occurred during sending",
  "إرسال للمحادثات المحددة": "Send to selected chats",
  "المشاركة للتطبيقات الخارجية 📲": "Share to external apps 📲",
  "واتساب": "WhatsApp",
  "فيسبوك": "Facebook",
  "تليجرام": "Telegram",
  "إكس": "X",
  "البث المباشر الحي 🔴": "Live Stream 🔴",
  "🎙️ شارك وانضم للبث المباشر الآن للاستماع والتفاعل!": "🎙️ Share and join the live stream now to listen and interact!",
  "تم فتح نافذة المشاركة بنجاح": "Sharing window opened successfully",
  "تم نسخ الرابط بنجاح (المتصفح لا يدعم المشاركة الأصلية)": "Link copied successfully (browser doesn't support native sharing)",
  "فتح قائمة مشاركة الهاتف الأصلية 📱": "Open native phone share menu 📱",
  "مالك البث 👑": "Stream Owner 👑",
  "مشرف البث 🛡️": "Stream Moderator 🛡️",
  "عضو عادي 👥": "Regular Member 👥",
  "عضو نشط ومتميز في مجتمع البث المباشر 🌟": "Active and distinguished member of the live community 🌟",
  "التحكم في الصوت": "Volume Control",
  "بصفتك مضيف/مشرف، يمكنك رفع صوت المشارك حتى 1000% لتضخيمه للجميع.": "As host/moderator, you can boost participant volume up to 1000% to amplify it for everyone.",
  "التحكم في صوت هذا المشارك محلياً على جهازك فقط.": "Control this participant's volume locally on your device only.",
  "إلغاء كتم الصوت (عبر الخادم) 🔊": "Unmute (Server-side) 🔊",
  "كتم الصوت (عبر الخادم) 🔇": "Mute (Server-side) 🔇",
  "تم إنزال الضيف": "Guest brought down",
  "للجمهور.": "to the audience.",
  "فشل إنزال الضيف": "Failed to bring down guest",
  "إزالة وإنزال للجمهور 👎": "Remove & demote to audience 👎",
  "🔒 لا يمكن كتم أو طرد المشرفين الآخرين لحفظ سلامة الغرفة. يمكنك فقط ضبط مستوى الصوت محلياً.": "🔒 Other moderators cannot be muted or kicked to preserve room integrity. You can only adjust volume locally.",
  "تم إلغاء الكتم المحلي لـ": "Local mute lifted for",
  "تم كتم صوت": "Muted",
  "محلياً لديك.": "locally for you.",
  "إلغاء كتم الصوت محلياً 🔊": "Unmute locally 🔊",
  "كتم الصوت محلياً (لي فقط) 🔇": "Mute locally (me only) 🔇",
  "إغلاق القائمة": "Close Menu",
  "إلغاء المتابعة 👤": "Unfollow 👤",
  "رد المتابعة 👥": "Follow Back 👥",
  "متابعة 👤": "Follow 👤",
  "تم تصغير شاشة": "Screen minimized for",
  "تم توسيع شاشة": "Screen maximized for",
  "تصغير 🔍": "Minimize 🔍",
  "توسيع 🔍": "Maximize 🔍",
  "إنزال 👎": "Bring Down 👎",
  "إلغاء صلاحيات المشرف 👥": "Revoke moderator privileges 👥",
  "تحويل لمشرف 🛡️": "Promote to moderator 🛡️",
  "طرد وإنزال للجمهور 👎": "Kick & demote to audience 👎",
  "📋 تم نسخ معرف الضيف بنجاح!": "📋 Guest ID copied successfully!",
  "نسخ معرف الضيف 📋": "Copy Guest ID 📋",
  "إغلاق": "Close",

  // Smart Whiteboard
  "السبورة الذكية التفاعلية 🎨": "Interactive Smart Whiteboard 🎨",
  "أنت ترسم الآن على سبورة مشتركة يراها الجميع بالوقت الفعلي 🎙️": "You are now drawing on a shared board that everyone sees in real-time 🎙️",
  "وضع المشاهدة فقط - يقوم المشرف بالرسم حالياً 🔒": "View-only mode - Moderator is currently drawing 🔒",
  "اللون:": "Color:",
  "مسح الكل": "Clear All",
  "إنهاء السبورة للجميع": "End Whiteboard for Everyone",
  "وضع المشاهدة فقط (المضيف يقوم بالشرح والرسم الآن)": "View-only mode (Host is currently explaining and drawing)",

  // Live Stream Bottom Sheets
  "تغيير خلفية البث المباشر 🖼️": "Change Live Stream Background 🖼️",
  "اختر استوديو افتراضي أو نمط خلفية ملون يظهر عند إيقاف الكاميرا": "Choose a virtual studio or colorful background style to show when the camera is off",
  "طبيعي": "Normal",
  "تغبيش": "Blur",
  "استوديو": "Studio",
  "نيون ريترو": "Neon Retro",
  "شاطئ تيل": "Teal Beach",
  "استوديو الهاتف": "Phone Gallery",
  "تم تطبيق خلفية:": "Background applied:",
  "مستويات تصفية وتنعيم البشرة ✨": "Skin Smoothing & Filter Levels ✨",
  "تحكم بمستوى تنعيم الوجه وتصفية البشرة في الوقت الفعلي خلال البث الحي": "Control skin smoothing and filtering level in real-time during live streaming",
  "تصفية خفيفة": "Light Filter",
  "تنعيم عالي": "High Smoothing",
  "تصفية سينمائية": "Cinematic Filter",
  "تم تفعيل:": "Enabled:",
  "مشغل وبث الصوتيات 🎵": "Audio Player & Streaming 🎵",
  "اختر ملف صوتي (MP3) لبثه مباشرة للمشاهدين بنقاء رقمي عالي": "Choose an audio file (MP3) to broadcast live to viewers with high digital clarity",
  "وضع الصراحة والأسئلة الشجاعة 🤫": "Truth or Dare Mode 🤫",
  "اختر سؤالاً صريحاً لعرضه مباشرة على شاشة البث للمناقشة والرد": "Choose a truth question to display live on the stream screen for discussion",
  "وضع الصراحة (الأسئلة مجهولة الهوية)": "Truth Mode (Anonymous Questions)",
  "عند التفعيل، يبدأ مؤقت 5 دقائق وكل التعليقات تُعرض بأسماء وصور مجهولة دائماً.": "When activated, a 5-minute timer starts and all comments are shown anonymously.",
  "تعطيل": "Disable",
  "تفعيل الوضع 🤫": "Activate Mode 🤫",
  "ما هو القرار الذي اتخذته وندمت عليه كثيراً في حياتك؟": "What is a decision you made that you regret deeply?",
  "إذا ربحت مليون دولار فجأة، ما هو أول شيء ستشتريه؟": "If you suddenly won a million dollars, what is the first thing you would buy?",
  "ما هي الصفة التي تكرهها جداً في الأشخاص القريبين منك؟": "What is a trait you strongly dislike in people close to you?",
  "لو أتيحت لك فرصة الاعتذار لشخص واحد اليوم، من سيكون؟": "If you had the chance to apologize to one person today, who would it be?",
  "ما هو الحلم الأكبر الذي تسعى لتحقيقه قبل نهاية العام?": "What is the biggest dream you seek to achieve before the end of the year?",
  "تم تفعيل ونشر سؤال الصراحة 🤫": "Truth question activated and posted 🤫",
  "اكتب سؤال صراحة مخصص لمتابعيك...": "Write a custom truth question for your followers...",
  "تم نشر سؤالك الصريح المخصص! 🤫": "Your custom truth question has been posted! 🤫",
  "نشر الآن": "Post Now",
  "وضع الصراحة والأسئلة": "Truth Mode & Questions",
  "تم إخفاء سؤال الصراحة 🤫": "Truth question hidden 🤫",
  "بدء تحدي المنافسة PK الحماسي ⚔️": "Start exciting PK Battle challenge ⚔️",
  "أطلق معركة تصويت تفاعلية بين فريقين بسباق سرعة ونقاط تشجيع": "Launch an interactive voting battle between two teams with speed and support points",
  "عنوان أو فكرة التحدي": "Challenge Title or Idea",
  "مثال: تحدي الضحك، جولة تبرعات، أسئلة ذكاء...": "Example: Laughter challenge, charity run, trivia...",
  "مدة التحدي": "Challenge Duration",
  "دقيقة واحدة": "1 Minute",
  "3 دقائق (موصى به)": "3 Minutes (Recommended)",
  "5 دقائق": "5 Minutes",
  "تحدي PK البث المباشر ⚔️": "Live Stream PK Battle ⚔️",
  "تم إطلاق معركة تحدي PK الحماسية! ⚔️🔥": "Exciting PK Battle has been launched! ⚔️🔥",
  "بدء معركة PK الآن ⚔️🚀": "Start PK Battle now ⚔️🚀",
  "تم نسخ التعليق إلى الحافظة 📋": "Comment copied to clipboard 📋",
  "نسخ نص التعليق 📋": "Copy comment text 📋",
  "تثبيت هذا التعليق 📌": "Pin this comment 📌",
  "إلغاء الإشراف عن المستخدم 🛡️": "Demote moderator 🛡️",
  "تعيين كمشرف للبث 🛡️": "Promote to moderator 🛡️",
  "كتم تعليقات هذا المستخدم 🔇": "Mute this user's comments 🔇",
  "حظر وطرد هذا المستخدم نهائياً 🚫": "Ban and kick this user permanently 🚫",
  "مشاركة البث المباشر 📢": "Share Live Stream 📢",
  "رابط البث السريع": "Quick Stream Link",
  "تم نسخ رابط البث بنجاح": "Stream link copied successfully",
  "نسخ الرابط": "Copy Link",
  "المشاركة للمحادثات الخاصة والدخول المباشر 💬": "Share to private chats & direct access 💬",
  "حدد الأشخاص لإرسال بطاقة بث مباشر تفاعلية لهم داخل المحادثة الخاصة لتمكينهم من الدخول مباشرة للتطبيق.": "Select users to send an interactive live stream card to their private chats for direct access.",
  "لا توجد محادثات خاصة نشطة حالياً": "No active private chats found",

  // Common UI Buttons / Actions
  "رجوع": "Back",
  "تراجع": "Cancel",
  "إلغاء": "Cancel",
  "تأكيد": "Confirm",
  "تحديث": "Update",
  "حفظ": "Save",
  "حذف": "Delete",
  "تم": "Done",
  "مغادرة": "Leave",
  "تجاهل": "Ignore",
  "موافق": "OK",
  "أرسل": "Send",
  "متابَع": "Following",

  // Warnings / Toasts / Alerts
  "نجاح": "Success",
  "خطأ": "Error",
  "حدث خطأ": "An error occurred",
  "تنبيه أمني": "Security Alert",
  "يرجى ملء جميع الحقول المطلوبة": "Please fill in all required fields",
  "تم حفظ الإعدادات بنجاح": "Settings saved successfully",

  // Group Call Screens
  "مكالمة TruCast الجماعية 🎧": "TruCast Group Call 🎧",
  "كتم المنضمين تلقائياً 🔇": "Mute participants on entry 🔇",
  "تم قفل المايك للمشاركين الجدد تلقائياً 🔇": "Muted new participants on entry 🔇",
  "تم إلغاء قفل كتم المنضمين": "Unmuted new participants on entry",
  "تم إلغاء الكتم الإجباري واستعادة صلاحيات": "Forced mute lifted and restored permissions for",
  "فشل استعادة صلاحيات العضو": "Failed to restore participant permissions",
  "تم كتم": "Forced muted",
  "إجبارياً وسحب صلاحياته": "and revoked their permissions",
  "فشل كتم صوت العضو إجبارياً": "Failed to force mute participant",
  "قام": "has",
  "برفع اليد لطلب إلغاء الكتم والتحدث!": "raised hand to request unmute and speak!",
  "تم كتم المنضم الجديد تلقائياً:": "Muted new participant on entry:",
  "خيارات متقدمة": "Advanced Options",
  "تم تفعيل عزل الضوضاء بالذكاء الاصطناعي 🎙️": "AI Noise Isolation enabled 🎙️",
  "تم إلغاء تفعيل عزل الضوضاء": "AI Noise Isolation disabled",
  "تقليل الضوضاء النشط": "Active Noise Isolation",
  "تصغير شاشة المكالمة": "Minimize call screen",
  "تصغير الشاشة": "Minimize Screen",
  "🎨 تم فتح السبورة التفاعلية!": "🎨 Interactive whiteboard opened!",
  "🎨 تم إغلاق السبورة": "🎨 Whiteboard closed",
  "السبورة الذكية": "Smart Whiteboard",
  "جاري الاتصال والتحقق من القنوات...": "Connecting and verifying channels...",
  "يرجى الانتظار لحين تحميل بث المشاركين": "Please wait while loading participants' feed",
  "أنت": "You",
  "طلب التحدث / رفع اليد": "Request to speak / Raise hand",
  "عضو نشط ومتميز 🌟": "Active and distinguished member 🌟",
  "كتم": "Mute",
  "إلغاء كتم": "Unmute",
  "مشرف 🛡️": "Moderator 🛡️",
  "عضو 👥": "Member 👥",
  "عضو نشط ومتميز في مجتمع TruCast 🌟": "Active and distinguished member of TruCast community 🌟",
  "التحكم في تضخيم الصوت": "Control Audio Amplification",
  "التحكم في مستوى الصوت": "Control Volume Level",
  "عرض الملف الشخصي للعضو": "View Member Profile",
  "عرض الملف الشخصي للمشرف": "View Moderator Profile",
  "عرض الملف الشخصي": "View Profile",
  "إلغاء الكتم الإجباري (استعادة الصلاحيات)": "Lift Forced Mute (Restore Permissions)",
  "كتم إجباري (سحب الصلاحيات والمايك والكاميرا)": "Force Mute (Revoke Permissions, Mic, & Camera)",
  "تم طرد العضو": "Kicked member",
  "وإزالته من المجموعة بنجاح": "and removed them from the group successfully",
  "فشل طرد العضو من المجموعة": "Failed to kick member from the group",
  "إزالة من المجموعة": "Remove from Group",
  "محلياً لديك": "locally for you",
  "🔊 إلغاء الكتم محلياً": "🔊 Unmute Locally",
  "🔇 كتم عندي فقط (محلي)": "🔇 Mute locally (me only)",
  "✋ تم إرسال طلب رفع اليد لفك الكتم إلى المشرفين!": "✋ Hand raised request sent to moderators!",
  "رفع اليد لطلب إلغاء الكتم": "Raise hand to request unmute",
  "إلغاء وإغلاق": "Cancel & Close",

  // Custom Settings (added for comprehensive translation)
  "تحليل التوجهات": "Trends Analysis",
  "مستوى التفاعل الأسبوعي": "Weekly Engagement Level",
  "مباشر": "Live",
  "إعدادات التنبيهات": "Notification Settings",
  "يجب تفعيل إذن التنبيهات من إعدادات المتصفح": "You must enable notification permission from browser settings",
  "تنبيهات الرسائل": "Message Alerts",
  "عندما تصلك رسالة خاصة جديدة من مستخدم آخر": "When you receive a new private message from another user",
  "تنبيهات البث المباشر": "Live Stream Alerts",
  "عندما يبدأ أحد صناع المحتوى بثاً مباشراً جديداً": "When a creator starts a new live stream",
  "تنبيهات التفاعلات المباشرة": "Live Interactions Alerts",
  "تلقي إشعارات فورية عند الإعجاب بمنشوراتك، التعليق عليها، مشاركتها أو متابعتك": "Receive instant notifications for likes, comments, shares, or follows",
  "تنبيهات النظام (Browser)": "System (Browser) Notifications",
  "تلقي إشعارات على جهازك حتى عند عدم استخدام التطبيق بنشاط": "Receive notifications on your device even when not actively using the app",
  "ميزة التنبيهات الذكية": "Smart Notifications Feature",
  "نقوم باستخدام تنبيهات لحظية لضمان عدم فوات أي لحظة مهمة في TruCast. يمكنك دائماً التحكم في نوع التنبيهات التي ترغب في استقبالها.": "We use real-time alerts to ensure you never miss an important moment on TruCast. You can always control which types of alerts you wish to receive.",
  "توثيق الحساب": "Account Verification",
  "طلب الحصول على شارة التوثيق الزرقاء 🛡️": "Request for blue verification badge 🛡️",
  "حسابك موثق بالفعل!": "Your account is already verified!",
  "لقد تم التحقق من هويتك ووثائقك بنجاح. حسابك يحمل الآن الشارة الزرقاء، مما يمنحك مصداقية أكبر وتفاعلاً مميزاً داخل مجتمع TruCast.": "Your identity and documents have been successfully verified. Your account now carries the blue badge, giving you more credibility and outstanding engagement within the TruCast community.",
  "حالة الحساب: موثق رسميًا": "Account Status: Officially Verified",
  "أدوات المطور والمحاكاة:": "Developer & Simulation Tools:",
  "إلغاء التوثيق (لأغراض الاختبار)": "Revoke Verification (for testing purposes)",
  "طلب التوثيق قيد المراجعة": "Verification Request Under Review",
  "لقد تلقينا وثائق الهوية الخاصة بك. يقوم فريق الإدارة بمراجعة الطلب للتحقق من مطابقة البيانات. يستغرق هذا الإجراء عادةً ما بين 24 إلى 48 ساعة.": "We have received your identity documents. The administration team is reviewing the request to match the data. This process usually takes 24 to 48 hours.",
  "حالة الطلب:": "Request Status:",
  "قيد الانتظار (Pending)": "Pending",
  "اسم مقدم الطلب:": "Applicant Name:",
  "لوحة تحكم محاكاة الإدارة (Admin Simulator):": "Admin Simulation Control Panel:",
  "موافقة الإدارة (Simulate Approve)": "Simulate Approve",
  "رفض الطلب (Simulate Reject)": "Simulate Reject",
  "تقدم بطلب توثيق حسابك": "Apply for Account Verification",
  "يرجى إرفاق صورة واضحة لبطاقة الهوية الوطنية أو جواز السفر الخاص بك لتأكيد هويتك وتفعيل الشارة الزرقاء.": "Please attach a clear photo of your national ID card or passport to confirm your identity and activate the blue badge.",
  "وثيقة الهوية الرسمية (ID Card / Passport)": "Official Identity Document (ID Card / Passport)",
  "تم اختيار الوثيقة. اضغط لتغييرها.": "Document selected. Click to change.",
  "اضغط هنا أو اسحب الملف لرفعه": "Click here or drag and drop to upload",
  "الصيغ المدعومة: PNG, JPG (الحد الأقصى: 2 ميجابايت)": "Supported formats: PNG, JPG (Max: 2MB)",
  "جاري إرسال الطلب...": "Submitting request...",
  "إرسال الوثائق للمراجعة": "Submit Documents for Review",
  "الإصدار v1.0.0 (Stable)": "Version v1.0.0 (Stable)",
  "مهمتنا": "Our Mission",
  "بناء مجتمع إبداعي يدعم صناع المحتوى في العالم العربي من خلال تقنيات الذكاء الاصطناعي وتوفير بيئة تواصل آمنة ومبدعة.": "Building a creative community that supports content creators in the Arab world through AI technologies and providing a safe and creative communication environment.",
  "الفريق": "The Team",
  "تم تطوير هذا التطبيق بواسطة فريق TruCast العالمي، بكل حب من أجل المبدعين.": "This application was developed by the global TruCast team, with love for creators.",
  "حقوق النشر © ٢٠٢٤ TruCast. جميع الحقوق محفوظة.": "Copyright © 2024 TruCast. All rights reserved.",
  "مقاطع الريلز": "Reels",
  "جميع المحفوظات": "All Saved Items",
  "مجلدات الحفظ": "Folders",
  "مجلد جديد": "New Folder",
  "إنشاء مجلد جديد": "Create New Folder",
  "اسم المجلد...": "Folder name...",
  "إنشاء": "Create",
  "المجلد فارغ": "The folder is empty",
  "حدث خطأ أثناء التحديث.": "An error occurred during update.",
  "البريد الحالي": "Current Email",
  "البريد الجديد": "New Email",
  "تحديث البريد": "Update Email",
  "المصادقة الثنائية (2FA)": "Two-Factor Authentication (2FA)",
  "نشط": "Active",
  "غير مفعل": "Disabled",
  "حماية حسابك برمز أمان إضافي عبر تطبيق مصادقة خارجي": "Protect your account with an additional security code from an external authenticator app",
  "إعداد التحقق بخطوتين (2FA)": "Set up Two-Factor Authentication (2FA)",
  "سوف يتطلب تسجيل الدخول إدخال رمز أمان من تطبيق مصادقة خارجي (مثل Google Authenticator أو Authy) بالإضافة إلى كلمة المرور الخاصة بك في كل مرة تسجل الدخول فيها.": "Logging in will require entering a security code from an external authenticator app (such as Google Authenticator or Authy) in addition to your password each time you log in.",
  "البدء بالتهيئة 🚀": "Start Setup 🚀",
  "1. افتح تطبيق المصادقة الخاص بك (Google Authenticator, Authy, Microsoft Authenticator).": "1. Open your authenticator app (Google Authenticator, Authy, Microsoft Authenticator).",
  "2. أضف حساباً جديداً يدويًا باستخدام مفتاح التهيئة أدناه أو امسح الرمز المرئي:": "2. Add a new account manually using the setup key below or scan the visible code:",
  "مفتاح التهيئة الخاص بك": "Your Setup Key",
  "تأكيد الرمز المكون من 6 أرقام": "Confirm 6-Digit Code",
  "تأكيد ومتابعة 🔒": "Confirm & Continue 🔒",
  "⚠️ هام جداً: احتفظ برموز الاستعادة الاحتياطية أدناه في مكان آمن. في حال فقدان تطبيق المصادقة أو الهاتف، لن تتمكن من دخول حسابك بدونها!": "⚠️ Very Important: Keep the backup recovery codes below in a safe place. If you lose your authenticator app or phone, you will not be able to access your account without them!",
  "نسخ رموز الاستعادة الاحتياطية 📋": "Copy Backup Recovery Codes 📋",
  "لقد قمت بحفظ الرموز، تفعيل 2FA الآن ✔️": "I have saved the codes, enable 2FA now ✔️",
  "تم تفعيل التحقق بخطوتين بنجاح!": "Two-Factor Authentication activated successfully!",
  "حسابك الآن محمي ومحصن بالكامل بمصادقة TOTP الذكية.": "Your account is now fully protected and secured with smart TOTP authentication.",
  "إغلاق 🔐": "Close 🔐",
  "تغيير كلمة المرور": "Change Password",
  "التشفير من طرف لطرف (E2EE)": "End-to-End Encryption (E2EE)",
  "يتم حماية محادثاتك بمفاتيح تشفير فريدة. مفتاحك الخاص مخزن محلياً فقط ولا يغادر جهازك أبداً.": "Your conversations are protected with unique encryption keys. Your private key is stored locally only and never leaves your device.",
  "إعادة تعيين مفاتيح التشفير": "Reset Encryption Keys",
  "الأجهزة المصرح لها بالدخول": "Authorized Devices",
  "إدارة الأجهزة والمتصفحات النشطة المصرح لها بالوصول إلى حسابك. يمكنك إلغاء ترخيص أي جهاز نشط لإخراجه فوراً.": "Manage active devices and browsers authorized to access your account. You can revoke access for any active device to log it out immediately.",
  "جاري تحميل الأجهزة...": "Loading devices...",
  "لا توجد أجهزة مسجلة حالياً": "No registered devices found",
  "محظور": "Blocked",
  "آخر ظهور:": "Last seen:",
  "الخصوصية والأمان المتقدم": "Privacy & Advanced Security",
  "أنت في بيئة آمنة": "You are in a safe environment",
  "TruCast مشفر تماماً ولا يشارك بياناتك مع أي طرف ثالث.": "TruCast is completely encrypted and does not share your data with any third party.",
  "عرض حالة النشاط": "Show Activity Status",
  "السماح للآخرين بمعرفة متى كنت متاحاً": "Allow others to see when you were available",
  "عرض أرقام المتابعين": "Show Followers Count",
  "إظهار عدد المتابعين في ملفك الشخصي": "Show followers count on your profile",
  "عرض عدد المنشورات": "Show Posts Count",
  "إظهار كمية المحتوى الذي شاركته": "Show the amount of content you shared",
  "الإحصائيات المجهولة": "Anonymous Statistics",
  "تبديل الأرقام الدقيقة إلى تقريبية (مثلاً 100+)": "Toggle exact numbers to approximate ones (e.g. 100+)",
  "تعطيل مؤشرات القراءة": "Disable Read Receipts",
  "منع الآخرين من معرفة قراءتك لرسائلهم مع حجب رؤيتك لمؤشراتهم": "Prevent others from knowing you read their messages while hiding their indicators from you",
  "إخفاء حالة النشاط تماماً": "Hide Activity Status Completely",
  "حجب الضوء الأخضر المتصل عن الأصدقاء نهائياً": "Completely hide the green online light from friends",
  "خصخصة قائمة المتابعة": "Make Following List Private",
  "منع الآخرين من تصفح قائمة الأشخاص الذين تتابعهم في حسابك": "Prevent others from browsing the list of people you follow in your account",
  "ميزة حصرية لمشتركي Premium لتعطيل مؤشرات القراءة وقراءة الرسائل بتخفٍّ كامل.": "An exclusive feature for Premium subscribers to disable read receipts and read messages in complete stealth.",
  "لماذا نعتمد هذا الأسلوب؟": "Why do we adopt this approach?",
  "في TruCast، نؤمن أن الخصوصية لا تعني الاختفاء، بل تعني السيطرة. الإحصائيات المجهولة تمنع التصنيف الاجتماعي المبني على الأرقام وتركز على جودة المحتوى.": "At TruCast, we believe privacy doesn't mean disappearing, it means control. Anonymous statistics prevent social ranking based on numbers and focus on the quality of content.",
  "إدارة قائمة الحظر": "Block List Management",
  "المستخدمون المدرجون في هذه القائمة لن يتمكنوا من مراسلتك، متابعتك، أو رؤية منشوراتك وبثك المباشر.": "Users on this list will not be able to message you, follow you, or see your posts and live streams.",
  "قائمة الحظر فارغة": "Block list is empty",
  "لم تقم بحظر أي مستخدم بعد.": "You haven't blocked any user yet.",
  "إلغاء الحظر": "Unblock",
  "تأكيد إلغاء الحظر": "Confirm Unblock",
  "هل أنت متأكد من رغبتك في إلغاء الحظر عن": "Are you sure you want to unblock",
  "سيتمكن مجدداً من رؤية منشوراتك، مراسلتك، ومتابعة حسابك.": "They will be able to see your posts, message you, and follow your account again.",
  "جاري الإلغاء...": "Unblocking...",

  // --- Profile & Group Details Screen (List 1) ---
  "منشور": "Post",
  "مكالمة نشطة": "Active Call",
  "مكالمة": "Call",
  "المعلومات": "Information",
  "إضافة أعضاء": "Add Members",
  "الوسائط المشتركة": "Shared Media",
  "الأعضاء": "Members",
  "مالك": "Owner",
  "عضو": "Member",
  "مشرف": "Moderator",

  // Additional detail terms
  "مكالمة نشطة الآن": "Active Call Now",
  "انضم للتواصل الصوتي والمرئي": "Join for voice and video communication",
  "انضم الآن": "Join Now",
  "إلغاء الكتم": "Unmute",
  "وصف": "Description",
  "ملف مشترك": "shared file",
  "لا توجد وسائط مشتركة": "No shared media",
  "لا توجد صور أو مقاطع فيديو مشتركة بعد": "No shared photos or videos yet",
  "تم إخفاء الأعضاء العاديين": "Regular members have been hidden",

  // --- Group Editing & Options Screen (List 2) ---
  "تعديل": "Edit",
  "اسم المجموعة": "Group Name",
  "اسم القناة": "Channel Name",
  "أدخل الاسم هنا...": "Enter name here...",
  "الوصف": "Description",
  "اكتب وصفاً مختصراً...": "Write a short description...",
  "الرابط المخصص": "Custom Link",
  "الإعدادات المتقدمة": "Advanced Settings",
  "التفاعلات": "Reactions",
  "الصلاحيات": "Permissions",
  "إدارة الصلاحيات": "Manage Permissions",
  "المشرفون": "Admins",
  "المكتومون": "Muted",
  "المحظورون": "Banned",
  "المكافح العنيف للإزعاج": "Aggressive Anti-Spam",
  "تصفية تلقائية متقدمة": "Advanced Auto-Filter",
  "إخفاء الأعضاء": "Hide Members",
  "فقط المشرفون يمكنهم رؤية القائمة": "Only admins can see the list",
  "حذف ومغادرة": "Delete & Leave",
  "المجموعة": "Group",
  "القناة": "Channel",

  // Group Details & Management additions
  "إدارة العضو": "Manage Member",
  "ترقية إلى مشرف": "Promote to Admin",
  "تنزيل لمستوى عضو (إلغاء الإشراف)": "Demote to Member (Cancel Admin)",
  "تعديل صلاحيات العضو": "Edit Member Permissions",
  "تأكيد إزالة العضو": "Confirm Member Removal",
  "لا يمكن إزالة مالك المجموعة!": "Cannot remove the group owner!",
  "عذراً، لا يمكن للمشرفين إزالة مشرفين آخرين.": "Sorry, moderators cannot remove other moderators.",
  "تم إزالة العضو من المجموعة بنجاح!": "Member removed from group successfully!",
  "حدث خطأ أثناء إزالة العضو من المجموعة": "An error occurred while removing member from group",
  "هل أنت متأكد من رغبتك في إزالة العضو ": "Are you sure you want to remove member ",
  " من المجموعة؟ لن يتمكن من قراءة أو كتابة أي رسائل بعد الآن.": " from the group? They will no longer be able to read or write messages.",
  "مشاركة الرابط": "Share Link",
  "مغادرة المجموعة": "Leave Group",
  "مغادرة القناة": "Leave Channel",
  "نمط التفاعلات": "Reactions Mode",
  "كل التفاعلات": "All Reactions",
  "السماح بجميع الرموز التعبيرية": "Allow all emojis",
  "بعض التفاعلات": "Some Reactions",
  "السماح برموز مختارة فقط": "Allow selected emojis only",
  "إيقاف التفاعلات": "Disable Reactions",
  "لا يسمح بالتفاعل على الرسائل": "No reactions allowed on messages",
  "تخصيص الرموز": "Customize Emojis",
  "إرسال رسائل نصية": "Send Text Messages",
  "إضافة مستخدمين": "Add Users",
  "تثبيت الرسائل": "Pin Messages",
  "تغيير معلومات المحادثة": "Change Chat Info",
  "إرسال الوسائط": "Send Media",
  "الصور": "Photos",
  "المقاطع المرئية": "Videos",
  "الملفات": "Files",
  "الموسيقى": "Music",
  "هذه الصلاحيات تنطبق على جميع أعضاء المجموعة الافتراضييين، يمكنك تخصيص صلاحيات المشرفين بشكل منفصل.": "These permissions apply to all default group members. You can customize admin permissions separately.",
  "الأعضاء الذين تم كتمهم": "Muted Members",
  "الأعضاء المكتومون لا يمكنهم إرسال رسائل أو التحدث في هذه المجموعة حتى يتم إلغاء كتمهم من قبل المشرفين.": "Muted members cannot send messages or speak in this group until they are unmuted by admins.",
  "الأعضاء المكتومون حالياً": "Currently Muted Members",
  "لا يوجد أعضاء مكتومون حالياً.": "No muted members currently.",
  "قائمة المحظورين من المجموعة": "Banned Members List",
  "الأعضاء المحظورون يطردون نهائياً ويتم إيقاف دخولهم أو انضمامهم للمجموعة مجدداً حتى يتم إلغاء حظرهم.": "Banned members are permanently expelled, and their re-entry is blocked until they are unbanned.",
  "المحظورون حالياً": "Currently Banned Members",
  "لا يوجد أعضاء محظورون حالياً.": "No banned members currently.",
  "تحقق ذكي لحماية المجموعة": "Smart check to protect the group",
  "إضافة مشرف (من قائمة الأعضاء)": "Add Admin (From Members List)",
  "المشرفون الحاليون": "Current Admins",
  "صلاحيات عامة": "General Permissions",
  "صلاحيات فردية": "Individual Permissions",
  "صلاحيات الأعضاء العامة (Members)": "General Member Permissions (Members)",
  "صلاحيات المشرفين العامة (Admins)": "General Admin Permissions (Admins)",
  "إرسال الرسائل": "Send Messages",
  "تغيير معلومات المجموعة": "Change Group Info",
  "ابحث باسم العضو أو المعرّف...": "Search by member name or ID...",
  "لم يتم العثور على أعضاء أعضاء مطابقة للبحث": "No matching members found",
  "لم يتم العثور على أعضاء مطابقة للبحث": "No matching members found",
  "مخصصة": "Custom",
  "تنزيل لمستوي عضو": "Demote to Member",
  "ترقية لمشرف": "Promote to Admin",
  "إعادة تعيين للوضع الافتراضي": "Reset to Default",
  "نمو القناة": "Channel Growth",
  "تحليل النشاط اليومي": "Daily Activity Analysis",
  "أعلى وقت للنشاط": "Peak Activity Time",
  "أكثر المواضيع تداولاً": "Most Discussed Topics",
  "معدل التفاعل للأعضاء": "Member Engagement Rate",
  "تحديثات التطبيق، دردشة عامة": "App updates, General chat",
  "ألوان السمة": "Theme Colors",
  "نمط الخلفية": "Background Style",
  "معاينة الرسالة": "Message Preview",
  "هذه هي طريقة ظهور رسائلك بالتنسيق الجديد!": "This is how your messages will appear in the new style!",
  "إيقاف": "Off",
  "5 ثواني": "5 seconds",
  "10 ثواني": "10 seconds",
  "30 ثانية": "30 seconds",
  "ساعة واحدة": "1 hour",
  "يوم واحد": "1 day",
  "ذاتي الاختفاء": "Self-destructing",
  "تصغير": "Zoom Out",
  "تكبير": "Zoom In",
  "فشل تحديث الصورة": "Failed to update image",
  "مؤقت التدمير الذاتي": "Self-Destruct Timer",
  "سيتم حذف الرسائل الجديدة تلقائياً للجميع بعد قراءتها بالمدة المحددة.": "New messages will be automatically deleted for everyone after they are read within the specified duration.",
  "تدمير ذاتي بعد: ": "Self-destruct in: ",
  "تدمير ذاتي ": "Self-destruct ",
  "ث": "s",
  "المظهر والتصميم": "Appearance & Design",
  "الرسائل المحفوظة": "Saved Messages",
  "مستخدم": "User",
  "الرابط المخصص قصير جداً (يجب أن يكون 3 أحرف على الأقل)": "Custom link is too short (must be at least 3 characters)",
  "الرابط المخصص محجوز بالفعل! يرجى اختيار رابط آخر.": "Custom link is already taken! Please choose another.",
  "جاري التحقق من التوفر...": "Checking availability...",
  "هذا الرابط متاح للاستخدام!": "This link is available!",
  "هذا الرابط محجوز بالفعل لمجموعة/قناة أخرى.": "This link is already reserved for another group/channel.",
  "يجب أن يتكون الرابط من 3 أحرف على الأقل.": "The link must be at least 3 characters long.",
  "يمكن للمستخدمين الآخرين العثور على": "Other users can find the",
  "والانضمام إليها مباشرةً عبر هذا الرابط.": "and join it directly through this link.",
  "الأمان والخصوصية": "Security & Privacy",
  "تراجع خطوة": "Undo",
  "إعادة": "Redo",
  "إعادة الضبط": "Reset",
  "إلغاء المعاينة": "Cancel Preview",
  "فلتر ومحسنات الصورة:": "Image Filters & Enhancers:",
  "طبيعي (بدون فلتر)": "✨ Natural (No filter)",
  "أبيض وأسود (Grayscale)": "🖤 Black & White (Grayscale)",
  "سيبيا دافئ (Sepia)": "⏳ Warm Sepia (Sepia)",
  "سطوع معزز (Brightness)": "☀️ Enhanced Brightness",
  "فلتر دافئ (Warm)": "🍁 Warm Filter",
  "فلتر بارد (Cool)": "❄️ Cool Filter",
  "تباين عالٍ (Contrast)": "🎯 High Contrast",
  "تكبير الصورة:": "Zoom Image:",
  "مفعل": "Enabled",
  "متوقفة": "Disabled",
  "الرسائل ذاتية الاختفاء": "Self-disappearing messages",
  "مستحدم TruCast": "TruCast User",
  "بواسطة المالك": "By Owner",
  "صلاحيات المشرف": "Admin Rights",
  "تم نسخ رابط المجموعة/القناة بنجاح!": "Group/Channel link copied successfully!",
  "تم نسخ الرابط المخصص بنجاح!": "Custom link copied successfully!",
  "تم إظهار جميع الأعضاء!": "All members shown!",
  "تم إخفاء الأعضاء العاديين!": "Regular members hidden!",
  "تأكيد الكتم الإجباري": "Confirm Force Mute",
  "تم كتم العضو بنجاح!": "Member muted successfully!",
  "تم إلغاء الكتم بنجاح!": "Mute lifted successfully!",
  "فشلت عملية إلغاء الكتم.": "Failed to lift mute.",
  "تم إلغاء حظر العضو بنجاح ويمكنه الانضمام مجدداً!": "Member unbanned successfully and can join again!",
  "فشلت عملية إلغاء الحظر.": "Failed to unban.",
  "تم تحديث رتبة المشرف بنجاح!": "Admin rank updated successfully!",
  "حدث خطأ أثناء تحديث الرتبة.": "An error occurred while updating rank.",
  "تم ترقية العضو إلى مشرف بنجاح!": "Member successfully promoted to admin!",
  "تم إلغاء صلاحيات الإشراف عن العضو بنجاح!": "Admin rights successfully removed!",
  "حدث خطأ أثناء تعديل صلاحيات العضو": "An error occurred while modifying member permissions.",
  "تم إلغاء الكتم عن العضو بنجاح!": "Member successfully unmuted!",
  "حدث خطأ أثناء تغيير حالة كتم العضو": "An error occurred while toggling member mute state.",
  "الأعضاء المكتومون": "Muted Members",
  "المحظورون 🚫": "Banned Members 🚫",
  "بدء مكالمة جماعية": "Start Group Call",
  "حذف الرسائل": "Delete Messages",
  "حظر المستخدمين": "Ban Users",
  "دعوة عبر الرابط": "Invite via Link",
  "إضافة مشرفين جدد": "Add New Admins",
  "نشط مؤخراً": "Recently Active",
  "رتبة المشرف": "Admin Rank",
  "وسم العضو (مثال: مؤسس)": "Member Label (e.g. Founder)",
  "هذا الوسم سيظهر بجانب اسم المشرف في الرسائل.": "This label will appear next to the admin name in messages.",
  "هل أنت متأكد من رغبتك في عزل هذا المشرف؟": "Are you sure you want to dismiss this admin?",
  "تم عزل المشرف بنجاح!": "Admin dismissed successfully!",
  "فشلت عملية عزل المشرف": "Failed to dismiss admin.",
  "عزل المشرف": "Dismiss Admin",
  "لا يمكنك عزل هذا المشرف": "You cannot dismiss this admin",
  "مكتوم": "Muted",
  "أعضاء": "Members",
  "صلاحيات": "Permissions",
  "متصل الآن": "Online",
  "دعوة برابط": "Invite via Link",
  "تعديل صلاحيات هذا العضو": "Edit permissions for this member",
  "عذراً، فقط مالك المجموعة والمشرفين يمكنهم تغيير إعدادات إخفاء الأعضاء.": "Sorry, only the group owner and admins can change member visibility settings.",
  "تم إخفاء قائمة الأعضاء بنجاح!": "Members list hidden successfully!",
  "تم إظهار قائمة الأعضاء بنجاح!": "Members list shown successfully!",
  "حدث خطأ أثناء تغيير إعدادات إخفاء الأعضاء.": "An error occurred while changing member visibility settings.",
  "عند التفعيل، سيتم إخفاء الأعضاء العاديين ويظهر فقط المالك والمشرفين للجميع.": "When enabled, normal members will be hidden, and only the owner and admins will be visible to everyone.",
  "هذا وسم سيظهر بجانب اسم المشرف في الرسائل.": "This label will appear next to the admin name in messages.",
  "مشاهدات": "Views",
  "تفاعل": "Engagement",
  "رابط_مخصص": "custom_link",
  "هل تريد تجاهل التغييرات؟": "Do you want to discard changes?",
  "المستخدمون النشطون": "Active Users",
  "قصص": "Stories",
  "اكتب رداً...": "Send a reply...",
  "مشاهدات القصة": "Story Views",
  "لا يوجد مشاهدات بعد 👁️": "No views yet 👁️",
  "قصتك": "Your Story",
  "تم إرسال ردك كرسالة خاصة! 📨": "Your reply was sent as a private message! 📨",
  "فشل إرسال الرد": "Failed to send reply",
  "تعديل القصة": "Edit Story",
  "تعديل التعليق": "Edit Comment",
  "نسخ": "Copy",
  "مشاركة في القصة": "Share to Story",
  "مشاركة في ريلز": "Share to Reels",
  "إلغاء التثبيت": "Unpin",
  "تثبيت التعليق": "Pin Comment",
  "حذف التعليق": "Delete Comment",
  "إبلاغ": "Report",
  "رد على": "Reply to",
  "حفظ التعديلات": "Save Changes",
  "تم استلام بلاغك، سنراجع التعليق": "Report received. We will review the comment.",
  "مجهول": "Anonymous",
  "أنشئ قصة متميزة واعرض تعليق هذا المتابع بأسلوب جذاب": "Create a featured story and display this comment in style",
  "إلغاء تثبيت التعليق": "Unpin Comment",
  "تثبيت التعليق 📌": "Pin Comment 📌",
  "إزالة هذا التعليق من العرض المثبت لجميع المتابعين": "Remove this comment from pinned view for all viewers",
  "عرض هذا التعليق كرسالة مثبتة في أعلى البث المباشر للجميع": "Show this comment as pinned message at the top for all viewers",
  "إلغاء كتم الصوت عن المتابع": "Unmute Viewer",
  "كتم المتابع": "Mute Viewer",
  "منعه من التعليق خلال البث النشط مع بقائه كمشاهد": "Prevent them from commenting during the active stream while remaining a viewer",
  "إلغاء حظر المتابع": "Unblock Viewer",
  "حظر وطرد المتابع فوراً": "Block & Kick Viewer Immediately",
  "طرده من البث المباشر نهائياً ومنع دخوله للبث مرة أخرى": "Permanently kick them from the live stream and prevent re-entry",
  "تنزيل رتبة الإشراف": "Demote Moderator",
  "تعيين كمشرف للبث": "Set as Stream Moderator",
  "منح المستخدم صلاحيات الإشراف وكتم المزعجين لمساعدتك في البث": "Grant moderator permissions to mute spammers and assist you in the stream",
  "إغلاق خيارات التعليق": "Close Comment Options",
  "إنهاء البث المباشر؟": "End Live Stream?",
  "مغادرة البث المباشر؟": "Leave Live Stream?",
  "هل أنت متأكد من رغبتك في إنهاء البث المباشر؟ سيتم إيقاف التشغيل وإنهاء البث لجميع المتابعين.": "Are you sure you want to end the live stream? The broadcast will be terminated for all viewers.",
  "هل أنت متأكد من رغبتك في مغادرة البث المباشر الحالي؟ يمكنك الانضمام مجدداً في أي وقت.": "Are you sure you want to leave the current live stream? You can rejoin at any time.",
  "طلب انضمام للبث (Guest) 🎙️": "Request to Join Stream (Guest) 🎙️",
  "إلغاء طلب الانضمام ⏳": "Cancel Join Request ⏳",
  "ارسل تعليقاً...": "Send a comment...",
  "📌 تعليق مثبت": "📌 Pinned Comment",
  "قائمة المتابعين مغلقة من قِبل المستخدم": "Followers list is closed by the user",
  "قائمة الأشخاص الذين يتابعهم هذا المستخدم خاصة": "The list of people followed by this user is private",
  "قائمة المتابعة مغلقة من قِبل المستخدم": "Following list is closed by the user",
  "تم حظر المستخدم وإلغاء المتابعة تلقائياً": "User blocked and unfollowed automatically",
  "لا توجد منشورات متاحة": "No posts available",
  "منصة التواصل الاجتماعي الذكية لمبدعي المستقبل": "The smart social platform for future creators",
  "تسجيل الدخول باستخدام جوجل": "Sign in with Google",
  "المتابعة بالبريد الإلكتروني": "Continue with Email",
  "تسجيل الدخول باستخدام فيسبوك": "Sign in with Facebook",
  "تسجيل الدخول باستخدام X": "Sign in with X",
  "تسجيل الدخول بالبريد": "Email Sign In",
  "إنشاء حساب جديد": "Create New Account",
  "بعد النقر على رابط التفعيل في بريدك الإلكتروني، اضغط على زر التحقق أدناه للمتابعة.": "After clicking the activation link in your email, click the verify button below to continue.",
  "تحقق الآن": "Verify Now",
  "إعادة إرسال الرابط": "Resend Link",
  "البريد الإلكتروني": "Email Address",
  "كلمة المرور": "Password",
  "ليس لديك حساب؟ ": "Don't have an account? ",
  "اضغط هنا لإنشاء حساب جديد": "Click here to create a new account",
  "لديك حساب بالفعل؟ ": "Already have an account? ",
  "اضغط هنا لتسجيل الدخول": "Click here to sign in",
  "أو": "or",
  "مركز الإشعارات": "Notification Center",
  "قراءة الكل": "Mark all as read",
  "البثوث": "Streams",
  "الإعجابات": "Likes",
  "المشاركات": "Shares",
  "المتابعة": "Follows",
  "لا توجد إشعارات حالياً": "No notifications currently",
  "بث مباشر نشط 🔴": "Active Live Stream 🔴",
  "بدأ المذيع أحمد بثاً مباشراً جديداً: نقاش ساخن حول تقنيات الويب": "Host Ahmed started a new live stream: A hot discussion about web technologies",
  "تعليق جديد 💬": "New Comment 💬",
  "علّقت سارة على منشورك: فكرة ممتازة جداً بالتوفيق!": "Sara commented on your post: Excellent idea, best of luck!",
  "إعجاب جديد ❤️": "New Like ❤️",
  "أعجب محمد بمنشورك الأخير حول خصوصية البيانات": "Mohamed liked your latest post about data privacy",
  "مشاركة جديدة 🔄": "New Share 🔄",
  "قام خالد بمشاركة منشورك بنسخ رابط المشاركة": "Khaled shared your post by copying the link",
  "متابعة جديدة 👤": "New Follower 👤",
  "بدأت ياسمين في متابعتك الآن، يمكنك تصفح حسابها": "Yasmin started following you, you can browse her profile",
  "استكشاف TruCast": "Explore TruCast",
  "ابحث عن مستخدمين بواسطة اسم المستخدم الخاص بهم": "Search for users by their username",
  "ابحث عن @username...": "Search for @username...",
  "منشور متداول": "trending post",
  "منشورات متداولة": "trending posts",
  "البحث عن": "Search for",
  "عرض كل النتائج لهذا البحث": "Show all results for this search",
  "منشورات": "posts",
  "الأكثر تداولاً": "Most Popular",
  "مبدعين": "Creators",
  "المستخدمين": "Users",
  "لم نجد مستخدمين": "No users found",
  "لم نجد منشورات": "No posts found",
  "استكشف العالم": "Explore the World",
  "بدون_اسم": "no_name",
  "هل تريد المغادرة؟": "Do you want to leave?",
  "هل أنت متأكد من رغبتك في مغادرة هذه القناة نهائياً؟": "Are you sure you want to leave this channel permanently?",
  "هل أنت متأكد من رغبتك في مغادرة هذه المجموعة نهائياً؟": "Are you sure you want to leave this group permanently?",
  "حذف المحادثة الخاصة؟": "Delete private chat?",
  "هل أنت متأكد من رغبتك في حذف هذه المحادثة الخاصة نهائياً؟ لا يمكن التراجع عن هذا الإجراء وسيتم مسح جميع الرسائل وملفات الوسائط من حسابك.": "Are you sure you want to permanently delete this private chat? This action cannot be undone and all messages and media files will be deleted from your account.",
  "مسح الرسائل المحفوظة؟": "Clear saved messages?",
  "هل أنت متأكد من رغبتك في مسح جميع رسائلك المحفوظة نهائياً؟ لا يمكن استعادتها لاحقاً.": "Are you sure you want to permanently clear all your saved messages? They cannot be recovered later.",
  "نعم، احذف": "Yes, delete",
  "بدء بث مباشر": "Start Live Stream",
  "شارك لحظاتك مع متابعيك في الوقت الفعلي": "Share your moments with your followers in real-time",
  "عنوان البث...": "Stream title...",
  "انطلق الآن": "Go Live Now",
};

// Comprehensive Kurdish (ku) Translation Dictionary
const kuTranslations: Record<string, string> = {
  "الرئيسية": "سەرەکی",
  "البث المباشر": "پەخشی ڕاستەوخۆ",
  "إضافة": "زیادکردن",
  "ريلز": "ڕیڵز",
  "حسابي": "پڕۆفایل",
  "الرسائل": "نامەکان",
  "الإعدادات": "ڕێکخستنەکان",
  "إعدادات الحساب": "ڕێکخستنی ئەکاونت",
  "تسجيل الخروج": "چوونەدەرەوە",
  "تسجيل الخروج من جميع الأجهزة": "چوونەدەرەوە لە هەموو ئامێرەکان",
  "حريتك في التعبير محمية بخصوصية مطلقة": "ئازادی ڕادەربڕینت بە پارێزراوی تەواو پارێزراوە",
  "الحساب": "ئەکاونت",
  "المزيد": "زیاتر",
  "تعديل البيانات الشخصية": "دەستکاریکردنی زانیارییە کەسییەکان",
  "تغيير البريد الإلكتروني": "گۆڕینی ناونیشانی ئیمەیڵ",
  "كلمة المرور والأمان": "نهێنوشە و پاراستن",
  "خصوصية الحساب": "تایبەتمەندێتی ئەکاونت",
  "قائمة الحظر": "لیستی بلۆککراوەکان",
  "المظهر": "شێواز",
  "تخصيص الأيقونات": "تایبەتکردنی ئایکۆنەکان",
  "تصميم الملف الشخصي": "دیزاینی پڕۆفایل",
  "توثيق الحساب (Verification)": "سەلماندنی ئەکاونت",
  "إحصائيات الحساب": "ئامارەکانی ئەکاونت",
  "التنبيهات": "ئاگادارکردنەوەکان",
  "المحفوظات": "پارێزراوەکان",
  "حول TruCast": "دەربارەی TruCast",
  "مركز المساعدة": "ناوەندی یارمەتی",
  "سياسة الخصوصية": "سیاسەتی تایبەتمەندێتی",
  "اللغة / Language": "زمان / Language",
  "تغيير لغة التطبيق": "گۆڕینی زمانی ئەپەکە",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "زمانی دڵخوازت هەڵبژێرە بۆ گەڕان لە تەواوی ئەپەکەدا",
  "اللغة الحالية": "زمانی ئێستا",
  "نجاح": "سەرکەوتوو",
  "خطأ": "هەڵە",
  "تم حفظ الإعدادات بنجاح": "ڕێکخستنەکان بە سەرکەوتوویی پاشەکەوت کران",
  "رجوع": "گەڕانەوە",
  "تراجع": "پاشگەزبوونەوە",
  "إلغاء": "هەڵوەشاندنەوە",
  "تأكيد": "پشتڕاستکردنەوە",
  "تحديث": "نوێکردنەوە",
  "حفظ": "پاشەکەوتکردن",
  "حذف": "سڕینەوە",
  "تم": "تەواو",
  "موافق": "باشە",
  "ماذا يدور في ذهنك؟": "چی لە مێشکتدایە؟",
  "إنشاء منشور": "دروستکردنی پۆست",
  "قصة جديدة": "چیرۆکی نوێ",
  "منشور نصي": "پۆستی دەقی",
  "صورة / فيديو": "وێنە / ڤیدیۆ",
  "مقطع ريلز": "ڤیدیۆی ڕیڵز",
  "التعليقات": "کۆمێنتەکان",
  "أضف تعليقاً...": "کۆمێنتێک زیاد بکە...",
  "نشر": "بڵاوکردنەوە",
  "مشاركة": "هاوبەشکردن",
  "إعجاب": "لایک",
  "متابعة": "فۆڵۆ بکە",
  "إلغاء المتابعة": "لابردنی فۆڵۆ",
  "مراسلة": "نامە بنێرە",
  "بحث": "گەڕان",
  "الرائجة": "باوەکان",
  "قصص نشطة": "چیرۆکە چالاکەکان",
  "البحث عن منشورات...": "گەڕان بۆ پۆستەکان...",
  "ذكاء اصطناعي": "زیرەکی دەستکرد",
  "اسحب للتحديث": "بکێشە بۆ نوێکردنەوە",
  "اترك للتحديث": "بەریبدە بۆ نوێکردنەوە",
  "جاري التحديث...": "نوێ دەکرێتەوە...",
  "لا توجد منشورات": "هیچ پۆستێک نەدۆزرایەوە",
  "المنشور متاح للجميع": "پۆستی گشتی",
  "المشتركين المميزين فقط": "تەنها بۆ بەشداربووانی تایبەت",
  "خيارات التصويت": "هەڵبژاردنەکانی ڕاپرسی",
  "إضافة خيار": "زیادکردنی بژاردە",
  "سؤال الاستطلاع": "پرسیاری ڕاپرسی",
  "تم نشر المنشور بنجاح!": "پۆستەکە بە سەرکەوتوویی بڵاوکرایەوە!",
  "حدث خطأ أثناء النشر": "هەڵەیەک لە کاتی بڵاوکردنەوەدا ڕوویدا",
};

// Comprehensive Persian (fa) Translation Dictionary
const faTranslations: Record<string, string> = {
  "الرئيسية": "خانه",
  "البث المباشر": "پخش زنده",
  "إضافة": "افزودن",
  "ريلز": "ریلز",
  "حسابي": "پروفایل",
  "الرسائل": "پیام‌ها",
  "الإعدادات": "تنظیمات",
  "إعدادات الحساب": "تنظیمات حساب",
  "تسجيل الخروج": "خروج از حساب",
  "تسجيل الخروج من جميع الأجهزة": "خروج از تمام دستگاه‌ها",
  "حريتك في التعبير محمية بخصوصية مطلقة": "آزادی بیان شما با حریم خصوصی مطلق محافظت می‌شود",
  "الحساب": "حساب کاربری",
  "المزيد": "بیشتر",
  "تعديل البيانات الشخصية": "ویرایش اطلاعات شخصی",
  "تغيير البريد الإلكتروني": "تغییر ایمیل",
  "كلمة المرور والأمان": "رمز عبور و امنیت",
  "خصوصية الحساب": "حریم خصوصی حساب",
  "قائمة الحظر": "لیست مسدود شده‌ها",
  "المظهر": "ظاهر برنامه",
  "تخصيص الأيقونات": "شخصی‌سازی آیکون‌ها",
  "تصميم الملف الشخصي": "طراحی پروفایل",
  "توثيق الحساب (Verification)": "تایید حساب کاربری",
  "إحصائيات الحساب": "آمار حساب",
  "التنبيهات": "اعلان‌ها",
  "المحفوظات": "ذخیره شده‌ها",
  "حول TruCast": "درباره TruCast",
  "مركز المساعدة": "مرکز پشتیبانی",
  "سياسة الخصوصية": "سیاست حفظ حریم خصوصی",
  "اللغة / Language": "زبان / Language",
  "تغيير لغة التطبيق": "تغییر زبان برنامه",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "زبان مورد نظر خود را برای مرور کل برنامه انتخاب کنید",
  "اللغة الحالية": "زبان فعلی",
  "نجاح": "موفقیت",
  "خطأ": "خطا",
  "تم حفظ الإعدادات بنجاح": "تنظیمات با موفقیت ذخیره شد",
  "رجوع": "بازگشت",
  "تراجع": "لغو",
  "إلغاء": "انصراف",
  "تأكيد": "تایید",
  "تحديث": "بروزرسانی",
  "حفظ": "ذخیره",
  "حذف": "حذف",
  "تم": "انجام شد",
  "موافق": "باشه",
  "ماذا يدور في ذهنك؟": "به چه چیزی فکر می‌کنید؟",
  "إنشاء منشور": "ایجاد پست",
  "قصة جديدة": "داستان جدید",
  "منشور نصي": "پست متنی",
  "صورة / فيديو": "عکس / ویدیو",
  "مقطع ريلز": "ویدیو ریلز",
  "التعليقات": "نظرات",
  "أضف تعليقاً...": "افزودن نظر...",
  "نشر": "ارسال پست",
  "مشاركة": "اشتراک‌گذاری",
  "إعجاب": "لایک",
  "متابعة": "دنبال کردن",
  "إلغاء المتابعة": "لغو دنبال کردن",
  "مراسلة": "ارسال پیام",
  "بحث": "جستجو",
  "الرائجة": "داغ‌ترین‌ها",
  "قصص نشطة": "داستان‌های فعال",
  "البحث عن منشورات...": "جستجوی پست‌ها...",
  "ذكاء اصطناعي": "دستیار هوش مصنوعی",
  "اسحب للتحديث": "برای بروزرسانی بکشید",
  "اترك للتحديث": "برای بروزرسانی رها کنید",
  "جاري التحديث...": "در حال بروزرسانی...",
  "لا توجد منشورات": "پستی یافت نشد",
  "المنشور متاح للجميع": "پست عمومی",
  "المشتركين المميزين فقط": "فقط مشترکین ویژه",
  "خيارات التصويت": "گزینه‌های نظرسنجی",
  "إضافة خيار": "افزودن گزینه",
  "سؤال الاستطلاع": "سوال نظرسنجی",
  "تم نشر المنشور بنجاح!": "پست با موفقیت منتشر شد!",
  "حدث خطأ أثناء النشر": "خطا در انتشار پست",
};

// Comprehensive Turkish (tr) Translation Dictionary
const trTranslations: Record<string, string> = {
  "الرئيسية": "Ana Sayfa",
  "البث المباشر": "Canlı Yayın",
  "إضافة": "Ekle",
  "ريلز": "Reels",
  "حسابي": "Profil",
  "الرسائل": "Mesajlar",
  "الإعدادات": "Ayarlar",
  "إعدادات الحساب": "Hesap Ayarları",
  "تسجيل الخروج": "Çıkış Yap",
  "تسجيل الخروج من جميع الأجهزة": "Tüm Cihazlardan Çıkış Yap",
  "حريتك في التعبير محمية بخصوصية مطلقة": "İfade özgürlüğünüz mutlak gizlilikle korunmaktadır",
  "الحساب": "Hesap",
  "المزيد": "Daha Fazla",
  "تعديل البيانات الشخصية": "Kişisel Bilgileri Düzenle",
  "تغيير البريد الإلكتروني": "E-postayı Değiştir",
  "كلمة المرور والأمان": "Şifre ve Güvenlik",
  "خصوصية الحساب": "Hesap Gizliliği",
  "قائمة الحظر": "Engellenenler Listesi",
  "المظهر": "Görünüm",
  "تخصيص الأيقونات": "Simgeleri Özelleştir",
  "تصميم الملف الشخصي": "Profil Tasarımı",
  "توثيق الحساب (Verification)": "Hesap Doğrulama",
  "إحصائيات الحساب": "Hesap İstatistikleri",
  "التنبيهات": "Bildirimler",
  "المحفوظات": "Favoriler",
  "حول TruCast": "TruCast Hakkında",
  "مركز المساعدة": "Yardım Merkezi",
  "سياسة الخصوصية": "Gizlilik Politikası",
  "اللغة / Language": "Dil / Language",
  "تغيير لغة التطبيق": "Uygulama Dilini Değiştir",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "Uygulamanın tamamına göz atmak için tercih ettiğiniz dili seçin",
  "اللغة الحالية": "Geçerli Dil",
  "نجاح": "Başarılı",
  "خطأ": "Hata",
  "تم حفظ الإعدادات بنجاح": "Ayarlar başarıyla kaydedildi",
  "رجوع": "Geri",
  "تراجع": "Vazgeç",
  "إلغاء": "İptal",
  "تأكيد": "Onayla",
  "تحديث": "Güncelle",
  "حفظ": "Kaydet",
  "حذف": "Sil",
  "تم": "Tamamlandı",
  "موافق": "Tamam",
  "ماذا يدور في ذهنك؟": "Aklından ne geçiyor?",
  "إنشاء منشور": "Gönderi Oluştur",
  "قصة جديدة": "Yeni Hikaye",
  "منشور نصي": "Yazı Gönderisi",
  "صورة / فيديو": "Fotoğraf / Video",
  "مقطع ريلز": "Reel Videosu",
  "التعليقات": "Yorumlar",
  "أضف تعليقاً...": "Yorum ekle...",
  "نشر": "Paylaş",
  "مشاركة": "Gönder",
  "إعجاب": "Beğen",
  "متابعة": "Takip Et",
  "إلغاء المتابعة": "Takibi Bırak",
  "مراسلة": "Mesaj Gönder",
  "بحث": "Ara",
  "الرائجة": "Trendler",
  "قصص نشطة": "Aktif Hikayeler",
  "البحث عن منشورات...": "Gönderi ara...",
  "ذكاء اصطناعي": "Yapay Zeka Asistanı",
  "اسحب للتحديث": "Yenilemek için çekin",
  "اترك للتحديث": "Yenilemek için bırakın",
  "جاري التحديث...": "Güncelleniyor...",
  "لا توجد منشورات": "Gönderi bulunamadı",
  "المنشور متاح للجميع": "Herkese Açık Gönderi",
  "المشتركين المميزين فقط": "Sadece Özel Aboneler",
  "خيارات التصويت": "Anket Seçenekleri",
  "إضافة خيار": "Seçenek Ekle",
  "سؤال الاستطلاع": "Anket Sorusu",
  "تم نشر المنشور بنجاح!": "Gönderi başarıyla paylaşıldı!",
  "حدث خطأ أثناء النشر": "Paylaşım sırasında hata oluştu",
};

// Comprehensive Spanish (es) Translation Dictionary
const esTranslations: Record<string, string> = {
  "الرئيسية": "Inicio",
  "البث المباشر": "En Vivo",
  "إضافة": "Añadir",
  "ريلز": "Reels",
  "حسابي": "Perfil",
  "الرسائل": "Mensajes",
  "الإعدادات": "Ajustes",
  "إعدادات الحساب": "Ajustes de Cuenta",
  "تسجيل الخروج": "Cerrar Sesión",
  "تسجيل الخروج من جميع الأجهزة": "Cerrar sesión en todos los dispositivos",
  "حريتك في التعبير محمية بخصوصية مطلقة": "Tu libertad de expresión está protegida con absoluta privacidad.",
  "الحساب": "Cuenta",
  "المزيد": "Más",
  "تعديل البيانات الشخصية": "Editar Datos Personales",
  "تغيير البريد الإلكتروني": "Cambiar Correo Electrónico",
  "كلمة المرور والأمان": "Contraseña y Seguridad",
  "خصوصية الحساب": "Privacidad de la Cuenta",
  "قائمة الحظر": "Lista de Bloqueados",
  "المظهر": "Apariencia",
  "تخصيص الأيقونات": "Personalizar Iconos",
  "تصميم الملف الشخصي": "Diseño del Perfil",
  "توثيق الحساب (Verification)": "Verificación",
  "إحصائيات الحساب": "Estadísticas de Cuenta",
  "التنبيهات": "Notificaciones",
  "المحفوظات": "Favoritos",
  "حول TruCast": "Acerca de TruCast",
  "مركز المساعدة": "Centro de Ayuda",
  "سياسة الخصوصية": "Política de Privacidad",
  "اللغة / Language": "Idioma / Language",
  "تغيير لغة التطبيق": "Cambiar Idioma de la Aplicación",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "Selecciona tu idioma preferido para navegar por toda la aplicación",
  "اللغة الحالية": "Idioma Actual",
  "نجاح": "Éxito",
  "خطأ": "Error",
  "تم حفظ الإعدادات بنجاح": "Ajustes guardados con éxito",
  "رجوع": "Atrás",
  "تراجع": "Cancelar",
  "إلغاء": "Cancelar",
  "تأكيد": "Confirmar",
  "تحديث": "Actualizar",
  "حفظ": "Guardar",
  "حذف": "Eliminar",
  "تم": "Hecho",
  "موافق": "Aceptar",
  "ماذا يدور في ذهنك؟": "¿Qué tienes en mente?",
  "إنشاء منشور": "Crear Publicación",
  "قصة جديدة": "Nueva Historia",
  "منشور نصي": "Publicación de Texto",
  "صورة / فيديو": "Foto / Video",
  "مقطع ريلز": "Video Reel",
  "التعليقات": "Comentarios",
  "أضف تعليقاً...": "Añadir un comentario...",
  "نشر": "Publicar",
  "مشاركة": "Compartir",
  "إعجاب": "Me gusta",
  "متابعة": "Seguir",
  "إلغاء المتابعة": "Dejar de seguir",
  "مراسلة": "Enviar Mensaje",
  "بحث": "Buscar",
  "الرائجة": "Tendencias",
  "قصص نشطة": "Historias Activas",
  "البحث عن منشورات...": "Buscar publicaciones...",
  "ذكاء اصطناعي": "Asistente de IA",
  "اسحب للتحديث": "Arrastra para actualizar",
  "اترك للتحديث": "Suelta para actualizar",
  "جاري التحديث...": "Actualizando...",
  "لا توجد منشورات": "No se encontraron publicaciones",
  "المنشور متاح للجميع": "Publicación Pública",
  "المشتركين المميزين فقط": "Solo Suscriptores Premium",
  "خيارات التصويت": "Opciones de Encuesta",
  "إضافة خيار": "Añadir Opción",
  "سؤال الاستطلاع": "Pregunta de Encuesta",
  "تم نشر المنشور بنجاح!": "¡Publicación publicada con éxito!",
  "حدث خطأ أثناء النشر": "Error al publicar la publicación",
};

// Comprehensive Russian (ru) Translation Dictionary
const ruTranslations: Record<string, string> = {
  "الرئيسية": "Главная",
  "البث المباشر": "Прямой эфир",
  "إضافة": "Добавить",
  "ريلز": "Reels",
  "حسابي": "Профиль",
  "الرسائل": "Сообщения",
  "الإعدادات": "Настройки",
  "إعدادات الحساب": "Настройки аккаунта",
  "تسجيل الخروج": "Выйти",
  "تسجيل الخروج من جميع الأجهزة": "Выйти на всех устройствах",
  "حريتك في التعبير محمية بخصوصية مطلقة": "Ваша свобода самовыражения защищена абсолютной конфиденциальностью.",
  "الحساب": "Аккаунт",
  "المزيد": "Еще",
  "تعديل البيانات الشخصية": "Личные данные",
  "تغيير البريد الإلكتروني": "Изменить эл. почту",
  "كلمة المرور والأمان": "Пароль и безопасность",
  "خصوصية الحساب": "Конфиденциальность",
  "قائمة الحظر": "Черный список",
  "المظهر": "Внешний вид",
  "تخصيص الأيقونات": "Настройка иконок",
  "تصميم الملف الشخصي": "Дизайн профиля",
  "توثيق الحساب (Verification)": "Верификация аккаунта",
  "إحصائيات الحساب": "Статистика аккаунта",
  "التنبيهات": "Уведомления",
  "المحفوظات": "Избранное",
  "حول TruCast": "О приложении TruCast",
  "مركز المساعدة": "Центр помощи",
  "سياسة الخصوصية": "Политика конфиденциальности",
  "اللغة / Language": "Язык / Language",
  "تغيير لغة التطبيق": "Изменить язык приложения",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "Выберите предпочтительный язык для всего приложения",
  "اللغة الحالية": "Текущий язык",
  "نجاح": "Успешно",
  "خطأ": "Ошибка",
  "تم حفظ الإعدادات بنجاح": "Настройки успешно сохранены",
  "رجوع": "Назад",
  "تراجع": "Отмена",
  "إلغاء": "Отмена",
  "تأكيد": "Подтвердить",
  "تحديث": "Обновить",
  "حفظ": "Сохранить",
  "حذف": "Удалить",
  "تم": "Готово",
  "موافق": "ОК",
  "ماذا يدور في ذهنك؟": "Что у вас нового?",
  "إنشاء منشور": "Создать публикацию",
  "قصة جديدة": "Новая история",
  "منشور نصي": "Текстовый пост",
  "صورة / فيديو": "Фото / Видео",
  "مقطع ريلز": "Видео Reels",
  "التعليقات": "Комментарии",
  "أضف تعليقاً...": "Добавить комментарий...",
  "نشر": "Опубликовать",
  "مشاركة": "Поделиться",
  "إعجاب": "Нравится",
  "متابعة": "Подписаться",
  "إلغاء المتابعة": "Отписаться",
  "مراسلة": "Написать",
  "بحث": "Поиск",
  "الرائجة": "Популярное",
  "قصص نشطة": "Активные истории",
  "البحث عن منشورات...": "Поиск публикаций...",
  "ذكاء اصطناعي": "ИИ-ассистент",
  "اسحب للتحديث": "Потяните для обновления",
  "اترك للتحديث": "Отпустите для обновления",
  "جاري التحديث...": "Обновление...",
  "لا توجد منشورات": "Публикаций не найдено",
  "المنشور متاح للجميع": "Публичный пост",
  "المشتركين المميزين فقط": "Только для премиум-подписчиков",
  "خيارات التصويت": "Варианты опроса",
  "إضافة خيار": "Добавить вариант",
  "سؤال الاستطلاع": "Вопрос опроса",
  "تم نشر المنشور بنجاح!": "Публикация успешно опубликована!",
  "حدث خطأ أثناء النشر": "Ошибка при публикации",
};

// Comprehensive German (de) Translation Dictionary
const deTranslations: Record<string, string> = {
  "الرئيسية": "Startseite",
  "البث المباشر": "Live",
  "إضافة": "Hinzufügen",
  "ريلز": "Reels",
  "حسابي": "Profil",
  "الرسائل": "Nachrichten",
  "الإعدادات": "Einstellungen",
  "إعدادات الحساب": "Kontoeinstellungen",
  "تسجيل الخروج": "Abmelden",
  "تسجيل الخروج من جميع الأجهزة": "Auf allen Geräten abmelden",
  "حريتك في التعبير محمية بخصوصية مطلقة": "Ihre Meinungsfreiheit ist durch absolute Privatsphäre geschützt.",
  "الحساب": "Konto",
  "المزيد": "Mehr",
  "تعديل البيانات الشخصية": "Persönliche Daten bearbeiten",
  "تغيير البريد الإلكتروني": "E-Mail-Adresse ändern",
  "كلمة المرور والأمان": "Passwort & Sicherheit",
  "خصوصية الحساب": "Kontoprivatsphäre",
  "قائمة الحظر": "Blockierungsliste",
  "المظهر": "Aussehen",
  "تخصيص الأيقونات": "Symbole anpassen",
  "تصميم الملف الشخصي": "Profilgestaltung",
  "توثيق الحساب (Verification)": "Konto-Verifizierung",
  "إحصائيات الحساب": "Kontostatistiken",
  "التنبيهات": "Benachrichtigungen",
  "المحفوظات": "Favoriten",
  "حول TruCast": "Über TruCast",
  "مركز المساعدة": "Hilfezentrum",
  "سياسة الخصوصية": "Datenschutz-Bestimmungen",
  "اللغة / Language": "Sprache / Language",
  "تغيير لغة التطبيق": "App-Sprache ändern",
  "اختر لغتك المفضلة لتصفح التطبيق بالكامل": "Wählen Sie Ihre bevorzugte Sprache für die gesamte App",
  "اللغة الحالية": "Aktuelle Sprache",
  "نجاح": "Erfolgreich",
  "خطأ": "Fehler",
  "تم حفظ الإعدادات بنجاح": "Einstellungen erfolgreich gespeichert",
  "رجوع": "Zurück",
  "تراجع": "Abbrechen",
  "إلغاء": "Abbrechen",
  "تأكيد": "Bestätigen",
  "تحديث": "Aktualisieren",
  "حفظ": "Speichern",
  "حذف": "Löschen",
  "تم": "Fertig",
  "موافق": "OK",
  "ماذا يدور في ذهنك؟": "Was geht dir durch den Kopf?",
  "إنشاء منشور": "Beitrag erstellen",
  "قصة جديدة": "Neue Story",
  "منشور نصي": "Textbeitrag",
  "صورة / فيديو": "Foto / Video",
  "مقطع ريلز": "Reel-Video",
  "التعليقات": "Kommentare",
  "أضف تعليقاً...": "Kommentar hinzufügen...",
  "نشر": "Veröffentlichen",
  "مشاركة": "Teilen",
  "إعجاب": "Gefällt mir",
  "متابعة": "Folgen",
  "إلغاء المتابعة": "Entfolgen",
  "مراسلة": "Nachricht senden",
  "بحث": "Suchen",
  "الرائجة": "Beliebt",
  "قصص نشطة": "Aktive Storys",
  "البحث عن منشورات...": "Beiträge suchen...",
  "ذكاء اصطناعي": "KI-Assistent",
  "اسحب للتحديث": "Zum Aktualisieren ziehen",
  "اترك للتحديث": "Zum Aktualisieren loslassen",
  "جاري التحديث...": "Wird aktualisiert...",
  "لا توجد منشورات": "Keine Beiträge gefunden",
  "المنشور متاح للجميع": "Öffentlicher Beitrag",
  "المشتركين المميزين فقط": "Nur für Premium-Abonnenten",
  "خيارات التصويت": "Umfrageoptionen",
  "إضافة خيار": "Option hinzufügen",
  "سؤال الاستطلاع": "Umfragefrage",
  "تم نشر المنشور بنجاح!": "Beitrag erfolgreich veröffentlicht!",
  "حدث خطأ أثناء النشر": "Fehler beim Veröffentlichen des Beitrags",
};

// Create Arabic dictionary as a fallback/mirror
const arTranslations: Record<string, string> = {
  "home_subtitle": "آخر الأخبار والمنشورات",
  "stories_title": "القصص اليومية",
  "stories_expire_hint": "تختفي بعد 24 ساعة",
  "add_story": "إضافة قصة",
  "watch_now": "شاهد الآن",
  "live_badge": "مباشر",
  "trending_now": "رائج الآن",
  "search_posts_placeholder": "بحث في المنشورات...",
  "profile_design_title": "تصميم الصفحة الشخصية",
  "premium_feature": "ميزة Premium",
  "premium_exclusive": "حصرية لمشتركي PREMIUM",
  "background_color": "لون الخلفية",
  "font_type": "نوع الخط",
  "font_inter": "Inter (افتراضي)",
  "font_mono": "Mono (تقني)",
  "font_serif": "Serif (كلاسيكي)",
  "font_black": "Black (عريض جداً)",
  "font_arabic_mono": "Arabic Mono (خط متسق)",
  "color_default": "افتراضي",
  "color_royal_blue": "أزرق ملكي",
  "color_deep_purple": "بنفسجي عميق",
  "color_emerald": "زمردي",
  "color_dark_red": "أحمر داكن",
  "color_velvet_orange": "برتقالي مخملي",
  "color_solid_gray": "رمادي صلب",
  "color_absolute_black": "أسود مطلق",
  "color_cold_dawn": "فجر بارد",
  "color_purple_dusk": "غسق بنفسجي",
  "color_red_energy": "طاقة حمراء",
  "color_sand_dune": "كثيب رملي",
  "chats_title": "المحادثات",
  "all_chats": "الكل",
  "chat_groups": "المجموعات",
  "chat_channels": "القنوات",
  "direct_messages": "الرسائل الخاصة",
  "no_messages_in_channel": "لا توجد رسائل في هذه القناة",
  "start_conversation_now": "ابدأ المحادثة الآن",
  "filter_newest": "الأحدث",
  "filter_oldest": "الأقدم",
  "filter_most_active": "الأكثر تفاعلاً",
  "المستخدمون النشطون": "المستخدمون النشطون",
  "قصص": "قصص",
  "اكتب رداً...": "اكتب رداً...",
  "مشاهدات القصة": "مشاهدات القصة",
  "لا يوجد مشاهدات بعد 👁️": "لا يوجد مشاهدات بعد 👁️",
  "قصتك": "قصتك",
  "تم إرسال ردك كرسالة خاصة! 📨": "تم إرسال ردك كرسالة خاصة! 📨",
  "فشل إرسال الرد": "فشل إرسال الرد",
  "تعديل القصة": "تعديل القصة",
};
Object.keys(enTranslations).forEach(key => {
  if (!arTranslations[key]) {
    arTranslations[key] = key;
  }
});

interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    return (localStorage.getItem('trucast_lang') as LanguageType) || 'ar';
  });

  const setLanguage = (lang: LanguageType) => {
    localStorage.setItem('trucast_lang', lang);
    setLanguageState(lang);
    
    // Set document direction and language code automatically
    if (lang === 'ar' || lang === 'ku' || lang === 'fa') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = lang;
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    // Initial load setup
    if (language === 'ar' || language === 'ku' || language === 'fa') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = language;
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string): string => {
    if (language === 'en') return enTranslations[key] || key;
    if (language === 'ku') return kuTranslations[key] || enTranslations[key] || key;
    if (language === 'fa') return faTranslations[key] || enTranslations[key] || key;
    if (language === 'tr') return trTranslations[key] || enTranslations[key] || key;
    if (language === 'es') return esTranslations[key] || enTranslations[key] || key;
    if (language === 'ru') return ruTranslations[key] || enTranslations[key] || key;
    if (language === 'de') return deTranslations[key] || enTranslations[key] || key;
    return arTranslations[key] || key; // 'ar' - default fallback
  };

  const isRtl = language === 'ar' || language === 'ku' || language === 'fa';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
